spring.application.name=module3
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/sys?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=10Vivek12#

#to auto load the data from data.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.inti.mode=always
spring.sql.init.data-locations=classpath:data.sql